#!/bin/bash

DIR=`dirname "$(readlink -f "$0")"`

if [ ! -d "src/deps/elona" ]; then
    ./runtime/setup
fi
./runtime/commit_hash

export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH
pushd $DIR/src
love .
popd
