#!/bin/bash

DIR=$(cd `dirname $0` && pwd)

if [ ! -d "src/deps/elona" ]; then
    ./runtime/setup
fi
./runtime/commit_hash

export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH
pushd $DIR/src > /dev/null
luajit opennefia.lua --working-dir "src/" "$@"
popd > /dev/null
