local ElonaPos = require("mod.elona.api.ElonaPos")
local Anim = require("mod.elona_sys.api.Anim")
local Gui = require("api.Gui")
local Chara = require("api.Chara")
local Tools = require("mod.tools.api.Tools")

local p = Chara.player()
local t = Tools.enemy()
local map = Chara.player():current_map()
local breath = ElonaPos.make_breath(p.x, p.y, t.x, t.y, 20, map)
local anim = Anim.breath(breath, "elona.lightning", p.x, p.y, t.x, t.y, map)
Gui.start_draw_callback(anim)
