return {
   -- PoS
   MEISHI = "名詞",
   KOYUUMEISHI = "固有名詞",
   DAIMEISHI = "代名詞",
   JODOUSHI = "助動詞",
   KAZU = "数",
   JOSHI = "助詞",
   SETTOUSHI = "接頭詞",
   DOUSHI = "動詞",
   KIGOU = "記号",
   FIRAA = "フィラー",
   SONOTA = "その他",
   KANDOUSHI = "感動詞",
   RENTAISHI = "連体詞",
   SETSUZOKUSHI = "接続詞",
   FUKUSHI = "副詞",
   SETSUZOKUJOSHI = "接続助詞",
   KEIYOUSHI = "形容詞",

   -- Pos2 and Inflection types
   HIJIRITSU = "非自立",
   FUKUSHIKANOU = "副詞可能",
   SAHENSETSUZOKU = "サ変接続",
   KEIYOUDOUSHIGOKAN = "形容動詞語幹",
   NAIKEIYOUSHIGOKAN = "ナイ形容詞語幹",
   JODOUSHIGOKAN = "助動詞語幹",
   FUKUSHIKA = "副詞化",
   TAIGENSETSUZOKU = "体言接続",
   RENTAIKA = "連体化",
   TOKUSHU = "特殊",
   SETSUBI = "接尾",
   SETSUZOKUSHITEKI = "接続詞的",
   DOUSHIHIJIRITSUTEKI = "動詞非自立的",
   SAHEN_SURU = "サ変・スル",
   TOKUSHU_TA = "特殊・タ",
   TOKUSHU_NAI = "特殊・ナイ",
   TOKUSHU_TAI = "特殊・タイ",
   TOKUSHU_DESU = "特殊・デス",
   TOKUSHU_DA = "特殊・ダ",
   TOKUSHU_MASU = "特殊・マス",
   TOKUSHU_NU = "特殊・ヌ",
   FUHENKAGATA = "不変化型",
   JINMEI = "人名",
   MEIREI_I = "命令ｉ",
   KAKARIJOSHI = "係助詞",
}
