local crop = {
   {
      name = "select_key",
      source = "graphic/interface.bmp",
      x = 0,
      y = 30,
      width = 24,
      height = 18,
   },
   {
      name = "tip_icons",
      source = "graphic/interface.bmp",
      x = 96,
      y = 360,
      width = 24,
      height = 16,
      count_x = 8
   },
   {
      name = "topic_icon",
      source = "graphic/interface.bmp",
      x = 120,
      y = 360,
      width = 24,
      height = 16,
   },
   {
      name = "input_caret",
      source = "graphic/interface.bmp",
      x = 0,
      y = 336,
      width = 12,
      height = 24,
   },
   {
      name = "gold_coin",
      source = "graphic/interface.bmp",
      x = 0,
      y = 392,
      width = 24,
      height = 24,
   },
   {
      name = "equipped",
      source = "graphic/interface.bmp",
      x = 12,
      y = 348,
      width = 12,
      height = 12,
   },
   {
      name = "label_input",
      source = "graphic/interface.bmp",
      x = 128,
      y = 288,
      width = 128,
      height = 32,
   },
   {
      name = "minimap_position",
      source = "graphic/interface.bmp",
      x = 15,
      y = 338,
      width = 6,
      height = 6,
   },
   {
      name = "interest_icon",
      source = "graphic/interface.bmp",
      x = 16,
      y = 360,
      width = 16,
      height = 16,
   },
   {
      name = "casino_title_decoration_left",
      source = "graphic/interface.bmp",
      x = 192,
      y = 360,
      width = 24,
      height = 16,
   },
   {
      name = "casino_title_decoration_right",
      source = "graphic/interface.bmp",
      x = 216,
      y = 360,
      width = 24,
      height = 16,
   },
   {
      name = "map_name_icon",
      source = "graphic/interface.bmp",
      x = 208,
      y = 376,
      width = 16,
      height = 16,
   },
   {
      name = "ime_status_english",
      source = "graphic/interface.bmp",
      x = 24,
      y = 336,
      width = 24,
      height = 24,
   },
   {
      name = "ime_status_japanese",
      source = "graphic/interface.bmp",
      x = 48,
      y = 336,
      width = 24,
      height = 24,
   },
   {
      name = "character_shadow",
      source = "graphic/interface.bmp",
      x = 240,
      y = 384,
      width = 32,
      height = 16,
   },
   {
      name = "camera",
      source = "graphic/interface.bmp",
      x = 240,
      y = 410,
      width = 24,
      height = 16,
   },
   {
      name = "hp_bar_frame",
      source = "graphic/interface.bmp",
      x = 312,
      y = 504,
      width = 104,
      height = 15,
   },
   {
      name = "furious_icon",
      source = "graphic/interface.bmp",
      x = 32,
      y = 608,
      width = 16,
      height = 16,
   },
   {
      name = "conquered_nefia_icon",
      source = "graphic/interface.bmp",
      x = 32,
      y = 624,
      width = 16,
      height = 16,
   },
   {
      name = "invaded_nefia_icon",
      source = "graphic/interface.bmp",
      x = 48,
      y = 624,
      width = 16,
      height = 16,
   },
   {
      name = "buff_icon_none",
      source = "graphic/interface.bmp",
      x = 320,
      y = 160,
      width = 32,
      height = 32,
   },
   {
      name = "quickmenu_action",
      source = "graphic/interface.bmp",
      x = 360,
      y = 144,
      width = 48,
      height = 48,
   },
   {
      name = "quickmenu_submenu",
      source = "graphic/interface.bmp",
      x = 360,
      y = 192,
      width = 48,
      height = 48,
   },
   {
      name = "inheritance_mark",
      source = "graphic/interface.bmp",
      x = 384,
      y = 360,
      width = 24,
      height = 24,
   },
   {
      name = "date_label_frame",
      source = "graphic/interface.bmp",
      x = 448,
      y = 376,
      width = 128,
      height = 24,
   },
   {
      name = "character_level_icon",
      source = "graphic/interface.bmp",
      x = 48,
      y = 392,
      width = 24,
      height = 24,
   },
   {
      name = "platinum_coin",
      source = "graphic/interface.bmp",
      x = 24,
      y = 392,
      width = 24,
      height = 24,
   },
   {
      name = "title_label_frame",
      source = "graphic/interface.bmp",
      x = 496,
      y = 581,
      width = 192,
      height = 18,
   },
   {
      name = "label_more",
      source = "graphic/interface.bmp",
      x = 552,
      y = 504,
      width = 120,
      height = 22,
   },
   {
      name = "label_more_scratch",
      source = "graphic/interface.bmp",
      x = 672,
      y = 504,
      width = 120,
      height = 24,
   },
   {
      name = "direction_arrow",
      source = "graphic/interface.bmp",
      x = 212,
      y = 432,
      width = 28,
      height = 28,
   },
   {
      name = "clock_hand",
      source = "graphic/interface.bmp",
      x = 0,
      y = 288,
      width = 48,
      height = 48,
   },
   {
      name = "hourglass",
      source = "graphic/interface.bmp",
      x = 72,
      y = 392,
      width = 24,
      height = 24,
   },
   {
      name = "failure_to_cast_effect",
      source = "graphic/item.bmp",
      x = 480,
      y = 0,
      width = 48,
      height = 48,
   },
   {
      name = "swarm_effect",
      source = "graphic/item.bmp",
      x = 816,
      y = 0,
      width = 48,
      height = 48,
   },
   {
      name = "breaking_effect",
      source = "graphic/item.bmp",
      x = 864,
      y = 0,
      width = 48,
      height = 48,
   },

   {
      name = "emotion_icons",
      source = "graphic/interface.bmp",
      x = 32,
      y = 608,
      width = 16,
      height = 16,
      count_x = 30,
   },
   {
      name = "blend_ingredient",
      source = "graphic/interface.bmp",
      x = 336,
      y = 360,
      width = 24,
      height = 24,
   },
   {
      name = "recipe_difficulty",
      source = "graphic/interface.bmp",
      x = 64,
      y = 624,
      width = 16,
      height = 16,
      count_x = 5,
   },
   {
      name = "card_front",
      source = "graphic/interface.bmp",
      x = 672,
      y = 216,
      width = 64,
      height = 96,
   },
   {
      name = "card_back",
      source = "graphic/interface.bmp",
      x = 736,
      y = 216,
      width = 64,
      height = 96,
   },
   {
      name = "card_scratch",
      source = "graphic/interface.bmp",
      x = 608,
      y = 216,
      width = 64,
      height = 96,
   },
   {
      name = "card_suit",
      source = "graphic/interface.bmp",
      x = 864,
      y = 533,
      width = 24,
      height = 32,
      count_x = 5,
   },
   {
      name = "card_rank",
      source = "graphic/interface.bmp",
      x = 864,
      y = 565,
      width = 24,
      height = 32,
      count_x = 13,
   },
   {
      name = "card_pile",
      source = "graphic/interface.bmp",
      x = 528,
      y = 216,
      width = 80,
      height = 112,
   },
   {
      name = "anim_bash",
      source = "graphic/interface.bmp",
      x = 816,
      y = 432,
      width = 48,
      height = 48,
      count_x = 4,
   },
   {
      name = "anim_slash",
      source = "graphic/interface.bmp",
      x = 1008,
      y = 432,
      width = 48,
      height = 48,
      count_x = 4,
   },
   {
      name = "arrow_left",
      source = "graphic/interface.bmp",
      x = 312,
      y = 336,
      width = 24,
      height = 24,
   },
   {
      name = "arrow_right",
      source = "graphic/interface.bmp",
      x = 336,
      y = 336,
      width = 24,
      height = 24,
   },
   {
      name = "ime_status_none",
      source = "graphic/interface.bmp",
      x = 72,
      y = 336,
      width = 24,
      height = 24,
   },
   {
      name = "ally_health_bar",
      source = "graphic/interface.bmp",
      x = 432,
      y = 517,
      width = 48,
      height = 3,
   },
   {
      name = "shadow",
      source = "graphic/interface.bmp",
      x = 0,
      y = 656,
      width = 24,
      height = 24,
      count_x = 8,
      count_y = 6,
   },
   {
      name = "shadow_spot",
      source = "graphic/interface.bmp",
      x = 144,
      y = 656,
      width = 24,
      height = 24,
      count_x = 2,
      count_y = 6,
   },
   {
      name = "shadow_edges",
      source = "graphic/interface.bmp",
      x = 192,
      y = 752,
      width = 48,
      height = 48,
      count_x = 17,
   },
   {
      name = "politics_law",
      source = "graphic/interface.bmp",
      x = 288,
      y = 360,
      width = 24,
      height = 24,
      count_x = 2,
   },
   {
      name = "radar_deco",
      source = "graphic/interface.bmp",
      x = 64,
      y = 288,
      width = 50,
      height = 32,
   },
   {
      name = "inventory_icons",
      source = "graphic/interface.bmp",
      x = 288,
      y = 48,
      width = 48,
      height = 48,
      count_x = 22,
   },
   {
      name = "message_symbol",
      source = "graphic/interface.bmp",
      x = 600,
      y = 360,
      width = 16,
      height = 16,
      count_x = 4,
   },
   {
      name = "message_window",
      source = "graphic/interface.bmp",
      x = 496,
      y = 528,
      width = 192,
      height = 72,
   },
   {
      name = "message_window_contents",
      source = "graphic/interface.bmp",
      x = 496,
      y = 536,
      width = 192,
      height = 64,
   },
   {
      name = "message_window_border",
      source = "graphic/interface.bmp",
      x = 496,
      y = 528,
      width = 192,
      height = 8,
   },
   {
      name = "mef_subref",
      source = "graphic/interface.bmp",
      x = 144,
      y = 624,
      width = 32,
      height = 32,
      count_x = 13,
   },
   {
      name = "light",
      source = "graphic/interface.bmp",
      x = 192,
      y = 704,
      width = 48,
      height = 48,
      count_x = 14,
   },
   {
      name = "body_part_icons",
      source = "graphic/interface.bmp",
      x = 600,
      y = 336,
      width = 24,
      height = 24,
      count_x = 11,
   },
   {
      name = "trait_icons",
      source = "graphic/interface.bmp",
      x = 384,
      y = 336,
      width = 24,
      height = 24,
      count_x = 6,
   },
   {
      name = "hud_skill_icons",
      source = "graphic/interface.bmp",
      x = 0,
      y = 376,
      width = 16,
      height = 16,
      count_x = 10,
   },
   {
      name = "hud_bar",
      source = "graphic/interface.bmp",
      x = 0,
      y = 440,
      width = 192,
      height = 24,
   },
   {
      name = "hud_minimap",
      source = "graphic/interface.bmp",
      x = 120,
      y = 504,
      width = 136,
      height = 88,
   },
   {
      name = "weather_particle",
      source = "graphic/interface.bmp",
      x = 0,
      y = 600,
      width = 8,
      height = 8,
      count_x = 4,
      count_y = 6,
   },
   {
      name = "minimap_scratch",
      source = "graphic/interface.bmp",
      x = 688,
      y = 528,
      width = 120,
      height = 84,
   },
   {
      name = "window",
      source = "graphic/interface.bmp",
      x = 0,
      y = 48,
      width = 264,
      height = 192,
   },
   {
      name = "window_1",
      source = "graphic/interface.bmp",
      x = 0,
      y = 240,
      width = 16,
      height = 16,
   },
   {
      name = "window_2",
      source = "graphic/interface.bmp",
      x = 48,
      y = 240,
      width = 16,
      height = 16,
   },
   {
      name = "window_3",
      source = "graphic/interface.bmp",
      x = 96,
      y = 240,
      width = 16,
      height = 16,
   },
   {
      name = "window_4",
      source = "graphic/interface.bmp",
      x = 144,
      y = 240,
      width = 16,
      height = 16,
   },
   {
      name = "window_5",
      source = "graphic/interface.bmp",
      x = 192,
      y = 240,
      width = 16,
      height = 16,
   },
   {
      name = "window_6",
      source = "graphic/interface.bmp",
      x = 240,
      y = 240,
      width = 16,
      height = 16,
   },
   {
      name = "hp_bar_ally",
      source = "graphic/interface.bmp",
      x = 432,
      y = 517,
      width = 48,
      height = 3,
   },
   {
      name = "hp_bar_other",
      source = "graphic/interface.bmp",
      x = 432,
      y = 513,
      width = 48,
      height = 3,
   },
   {
      name = "spot_light",
      source = "graphic/interface.bmp",
      x = 800,
      y = 112,
      width = 144,
      height = 144,
   },
   {
      name = "hud_hp_bar",
      source = "graphic/interface.bmp",
      x = 312,
      y = 520,
      width = 100,
      height = 6,
   },
   {
      name = "hud_mp_bar",
      source = "graphic/interface.bmp",
      x = 432,
      y = 520,
      width = 100,
      height = 6,
   },
   {
      name = "attributes_bar",
      source = "graphic/interface.bmp",
      x = 0,
      y = 440,
      width = 64,
      height = 16,
   },
   {
      name = "clock",
      source = "graphic/interface.bmp",
      x = 448,
      y = 408,
      width = 120,
      height = 96,
   },
   {
      name = "status_effect_bar",
      source = "graphic/interface.bmp",
      x = 0,
      y = 416,
      width = 80,
      height = 15,
   },
   {
      name = "caption",
      source = "graphic/interface.bmp",
      x = 672,
      y = 477,
      width = 128,
      height = 25,
   },
   {
      name = "list_scratch",
      source = "graphic/interface.bmp",
      x = 264,
      y = 96,
      width = 480,
      height = 19,
   },
   {
      name = "list_bullet",
      source = "graphic/interface.bmp",
      x = 48,
      y = 360,
      width = 16,
      height = 16,
   },
   {
      name = "enchantment_icons",
      source = "graphic/interface.bmp",
      x = 72,
      y = 336,
      width = 24,
      height = 24,
      count_x = 10,
   },
   {
      name = "skill_icons",
      source = "graphic/item.bmp",
      x = 0,
      y = 672,
      width = 48,
      height = 48,
      count_x = 8,
   },
   {
      name = "scene_title",
      source = "graphic/interface.bmp",
      x = 456,
      y = 144,
      width = 344,
      height = 72,
   },

   {
      name = "deco_cm",
      source = "graphic/deco_cm.bmp",
      x = 0,
      y = 0,
      width = 240,
      height = 264,
   },

   {
      name = "cloud1",
      source = "graphic/map0.bmp",
      x = 288,
      y = 1040,
      width = 208,
      height = 160,
   },
   {
      name = "cloud2",
      source = "graphic/map0.bmp",
      x = 0,
      y = 976,
      width = 288,
      height = 224,
   },

   {
      name = "deco_blend_a",
      source = "graphic/deco_blend.bmp",
      x = 0,
      y = 192,
      width = 480,
      height = 68,
   },
   {
      name = "deco_blend_b",
      source = "graphic/deco_blend.bmp",
      x = 80,
      y = 0,
      width = 160,
      height = 70,
   },
   {
      name = "deco_blend_c",
      source = "graphic/deco_blend.bmp",
      x = 0,
      y = 0,
      width = 80,
      height = 90,
   },

   {
      name = "deco_inv_a",
      source = "graphic/deco_inv.bmp",
      x = 0,
      y = 0,
      width = 144,
      height = 48,
   },
   {
      name = "deco_inv_b",
      source = "graphic/deco_inv.bmp",
      x = 0,
      y = 48,
      width = 48,
      height = 72,
   },
   {
      name = "deco_inv_c",
      source = "graphic/deco_inv.bmp",
      x = 48,
      y = 48,
      width = 48,
      height = 72,
   },
   {
      name = "deco_inv_d",
      source = "graphic/deco_inv.bmp",
      x = 0,
      y = 120,
      width = 48,
      height = 72,
   },

   {
      name = "deco_help_a",
      source = "graphic/deco_help.bmp",
      x = 0,
      y = 0,
      width = 48,
      height = 48,
   },
   {
      name = "deco_help_b",
      source = "graphic/deco_help.bmp",
      x = 0,
      y = 48,
      width = 96,
      height = 120,
   },

   {
      name = "deco_mirror_a",
      source = "graphic/deco_mirror.bmp",
      x = 0,
      y = 0,
      width = 48,
      height = 120,
   },

   {
      name = "deco_politics_a",
      source = "graphic/deco_politics.bmp",
      x = 0,
      y = 0,
      width = 128,
      height = 128,
   },
   {
      name = "deco_politics_b",
      source = "graphic/deco_politics.bmp",
      x = 0,
      y = 192,
      width = 144,
      height = 24,
   },

   {
      name = "deco_board_a",
      source = "graphic/deco_board.bmp",
      x = 0,
      y = 0,
      width = 128,
      height = 128,
   },
   {
      name = "deco_board_b",
      source = "graphic/deco_board.bmp",
      x = 0,
      y = 144,
      width = 48,
      height = 84,
   },

   {
      name = "deco_wear_a",
      source = "graphic/deco_wear.bmp",
      x = 0,
      y = 0,
      width = 96,
      height = 120,
   },
   {
      name = "deco_wear_b",
      source = "graphic/deco_wear.bmp",
      x = 0,
      y = 120,
      width = 72,
      height = 144,
   },

   {
      name = "deco_feat_a",
      source = "graphic/deco_feat.bmp",
      x = 0,
      y = 0,
      width = 48,
      height = 192,
   },
   {
      name = "deco_feat_b",
      source = "graphic/deco_feat.bmp",
      x = 48,
      y = 0,
      width = 48,
      height = 144,
   },
   {
      name = "deco_feat_c",
      source = "graphic/deco_feat.bmp",
      x = 0,
      y = 192,
      width = 96,
      height = 72,
   },
   {
      name = "deco_feat_d",
      source = "graphic/deco_feat.bmp",
      x = 48,
      y = 144,
      width = 96,
      height = 48,
   },

   {
      name = "deco_skill_a",
      source = "graphic/deco_skill.bmp",
      x = 0,
      y = 0,
      width = 72,
      height = 144,
   },
   {
      name = "deco_skill_b",
      source = "graphic/deco_skill.bmp",
      x = 72,
      y = 0,
      width = 102,
      height = 48,
   },

   {
      name = "deco_spell_a",
      source = "graphic/deco_spell.bmp",
      x = 0,
      y = 0,
      width = 72,
      height = 144,
   },
   {
      name = "deco_spell_b",
      source = "graphic/deco_spell.bmp",
      x = 72,
      y = 0,
      width = 72,
      height = 96,
   },

   {
      name = "buff_icon",
      source = "graphic/character.bmp",
      x = 0,
      y = 1120,
      width = 32,
      height = 32,
      count_x = 29,
   },
   -- {
   --   name = "growth_buff_icon",
   --    source = "graphic/character.bmp",
   --    x = 640,
   --    y = 1120,
   --    width = 32,
   --    height = 32,
   --    count_x = 10,
   -- },

   {
      name = "deco_card_a",
      source = "graphic/deco_card.bmp",
      x = 0,
      y = 0,
      width = 128,
      height = 128,
   },
}

local function gen_crop_list(list)
   for _, v in ipairs(list) do
      v.type = "crop"
      v.output = string.format("graphic/asset/%s.png", v.name)
      v.combine_multiple = true
   end
end

gen_crop_list(crop)


local function gen_convert(name, no_alpha)
   return {
      name = name,
      type = "convert",
      no_alpha = no_alpha,
      source = string.format("graphic/%s.bmp", name),
      output = string.format("graphic/asset/%s.png", name)
   }
end

local convert = {
   gen_convert("g1"),
   gen_convert("g2"),
   gen_convert("g3"),
   gen_convert("g4"),
   gen_convert("g5"),
   gen_convert("g6"),
   gen_convert("g7"),
   gen_convert("g8"),

   gen_convert("bg1"),
   gen_convert("bg2"),
   gen_convert("bg3"),
   gen_convert("bg4"),
   gen_convert("bg5"),
   gen_convert("bg6"),
   gen_convert("bg7"),
   gen_convert("bg8"),
   gen_convert("bg9"),
   gen_convert("bg10"),
   gen_convert("bg11"),
   gen_convert("bg12"),
   gen_convert("bg13"),
   gen_convert("bg14"),
   gen_convert("bg15"),
   gen_convert("bg16"),
   gen_convert("bg17"),
   gen_convert("bg18"),
   gen_convert("bg19"),
   gen_convert("bg20"),
   gen_convert("bg21"),
   gen_convert("bg22"),

   gen_convert("bg_altar"),
   gen_convert("bg_card"),
   gen_convert("bg_night"),
   gen_convert("title", true),
   gen_convert("void", true),
   gen_convert("paper"),
   gen_convert("book"),

   gen_convert("bg_re10"),
   gen_convert("bg_re11"),
   gen_convert("bg_re12"),
   gen_convert("bg_re13"),
   gen_convert("bg_re14"),
   gen_convert("bg_re15"),
   gen_convert("bg_re1"),
   gen_convert("bg_re2"),
   gen_convert("bg_re3"),
   gen_convert("bg_re4"),
   gen_convert("bg_re5"),
   gen_convert("bg_re6"),
   gen_convert("bg_re7"),
   gen_convert("bg_re8"),
   gen_convert("bg_re9"),

   gen_convert("ie_sheet"),
   gen_convert("ie_chat"),
   gen_convert("ie_scroll"),
}

return {
   crop = crop,
   convert = convert,
}
