local chara = {
   { id = 0,   name = "blank" },
   { id = 1,   name = "human_male" },
   { id = 2,   name = "human_female" },
   { id = 3,   name = "elea_male" },
   { id = 4,   name = "elea_female" },
   { id = 5,   name = "eulderna_male" },
   { id = 6,   name = "eulderna_female" },
   { id = 7,   name = "trainer_male" },
   { id = 8,   name = "miches" },
   { id = 9,   name = "juere_male" },
   { id = 10,  name = "juere_female" },
   { id = 11,  name = "_11" },
   { id = 12,  name = "_12" },
   { id = 13,  name = "wizard_male" },
   { id = 14,  name = "wizard_female" },
   { id = 15,  name = "informer_male" },
   { id = 16,  name = "informer_female" },
   { id = 17,  name = "_17" },
   { id = 18,  name = "_18" },
   { id = 19,  name = "_19" },
   { id = 20,  name = "warrior_female" },
   { id = 21,  name = "warrior_male" },
   { id = 22,  name = "_22" },
   { id = 23,  name = "moyer_the_crooked" },
   { id = 24,  name = "_24" },
   { id = 25,  name = "guard" },
   { id = 26,  name = "_26" },
   { id = 27,  name = "punk_female" },
   { id = 28,  name = "_28" },
   { id = 29,  name = "_29" },
   { id = 30,  name = "_30" },
   { id = 31,  name = "gangster_male" },
   { id = 32,  name = "_32" },
   { id = 33,  name = "_33" },
   { id = 34,  name = "warrior_of_elea_female" },
   { id = 35,  name = "_35" },
   { id = 36,  name = "gangster_female" },
   { id = 37,  name = "fallen_soldier" },
   { id = 38,  name = "_38" },
   { id = 39,  name = "_39" },
   { id = 40,  name = "_40" },
   { id = 41,  name = "arena_master" },
   { id = 42,  name = "wizard_of_elea_female" },
   { id = 43,  name = "_43" },
   { id = 44,  name = "_44" },
   { id = 45,  name = "_45" },
   { id = 46,  name = "_46" },
   { id = 47,  name = "wizard_of_elea_male" },
   { id = 48,  name = "_48" },
   { id = 49,  name = "_49" },
   { id = 50,  name = "_50" },
   { id = 51,  name = "_51" },
   { id = 52,  name = "_52" },
   { id = 53,  name = "_53" },
   { id = 54,  name = "_54" },
   { id = 55,  name = "_55" },
   { id = 56,  name = "_56" },
   { id = 57,  name = "mercenary_archer" },
   { id = 58,  name = "_58" },
   { id = 59,  name = "_59" },
   { id = 60,  name = "_60" },
   { id = 61,  name = "_61" },
   { id = 62,  name = "_62" },
   { id = 63,  name = "_63" },
   { id = 64,  name = "_64" },
   { id = 65,  name = "_65" },
   { id = 66,  name = "dwarf" },
   { id = 67,  name = "_67" },
   { id = 68,  name = "_68" },
   { id = 69,  name = "healer" },
   { id = 70,  name = "rich_person_female" },
   { id = 71,  name = "rich_person_male" },
   { id = 72,  name = "noble_child_female" },
   { id = 73,  name = "noble_child_male" },
   { id = 74,  name = "palmian_elite_soldier_male" },
   { id = 75,  name = "palmian_elite_soldier_female" },
   { id = 76,  name = "thief_guild_member_male" },
   { id = 77,  name = "thief_guild_member_female" },
   { id = 78,  name = "fighter_guild_member_male" },
   { id = 79,  name = "fighter_guild_member_female" },
   { id = 80,  name = "fray" },
   { id = 81,  name = "_81" },
   { id = 82,  name = "_82" },
   { id = 83,  name = "_83" },
   { id = 84,  name = "_84" },
   { id = 85,  name = "_85" },
   { id = 86,  name = "_86" },
   { id = 87,  name = "_87" },
   { id = 88,  name = "_88" },
   { id = 89,  name = "_89" },
   { id = 90,  name = "_90" },
   { id = 91,  name = "_91" },
   { id = 92,  name = "_92" },
   { id = 93,  name = "_93" },
   { id = 94,  name = "_94" },
   { id = 95,  name = "_95" },
   { id = 96,  name = "_96" },
   { id = 97,  name = "_97" },
   { id = 98,  name = "_98" },
   { id = 99,  name = "karam" },
   { id = 100, name = "mercenary_wizard" },
   { id = 101, name = "_101" },
   { id = 102, name = "beggar_male" },
   { id = 103, name = "beggar_female" },
   { id = 104, name = "maid_male" },
   { id = 105, name = "maid_female" },
   { id = 106, name = "old_person_male" },
   { id = 107, name = "old_person_female" },
   { id = 108, name = "_108" },
   { id = 109, name = "shena" },
   { id = 110, name = "_110" },
   { id = 111, name = "_111" },
   { id = 112, name = "punk_male" },
   { id = 113, name = "_113" },
   { id = 114, name = "_114" },
   { id = 115, name = "_115" },
   { id = 116, name = "xabi" },
   { id = 117, name = "test_subject" },
   { id = 118, name = "_118" },
   { id = 119, name = "captain" },
   { id = 120, name = "sailor_male" },
   { id = 121, name = "sailor_female" },
   { id = 122, name = "tourist_male" },
   { id = 123, name = "_123" },
   { id = 124, name = "_124" },
   { id = 125, name = "_125" },
   { id = 126, name = "_126" },
   { id = 127, name = "citizen_of_cyber_dome2_male" },
   { id = 128, name = "citizen_of_cyber_dome_male" },
   { id = 129, name = "citizen_of_cyber_dome_female" },
   { id = 130, name = "_130" },
   { id = 131, name = "citizen_of_cyber_dome2_female" },
   { id = 132, name = "_132" },
   { id = 133, name = "_133" },
   { id = 134, name = "citizen2_male" },
   { id = 135, name = "citizen2_female" },
   { id = 136, name = "citizen_male" },
   { id = 137, name = "citizen_female" },
   { id = 138, name = "baker" },
   { id = 139, name = "mercenary_male" },
   { id = 140, name = "shopkeeper_male" },
   { id = 141, name = "shopkeeper_female" },
   { id = 142, name = "elder_male" },
   { id = 143, name = "elder_female" },
   { id = 144, name = "bartender_male" },
   { id = 145, name = "bartender_female" },
   { id = 146, name = "sales_person_male" },
   { id = 147, name = "sales_person_female" },
   { id = 148, name = "bard" },
   { id = 149, name = "_149" },
   { id = 150, name = "rogue_boss" },
   { id = 151, name = "_151" },
   { id = 152, name = "_152" },
   { id = 153, name = "_153" },
   { id = 154, name = "_154" },
   { id = 155, name = "_155" },
   { id = 156, name = "_156" },
   { id = 157, name = "rogue_wizard" },
   { id = 158, name = "rogue_archer" },
   { id = 159, name = "mercenary_warrior" },
   { id = 160, name = "_160" },
   { id = 161, name = "_161" },
   { id = 162, name = "_162" },
   { id = 163, name = "nun" },
   { id = 164, name = "_164" },
   { id = 165, name = "orc" },
   { id = 166, name = "master_thief" },
   { id = 167, name = "zombie" },
   { id = 168, name = "race_slime" },
   { id = 169, name = "rabbit" },
   { id = 170, name = "sheep" },
   { id = 171, name = "kobold" },
   { id = 172, name = "frog" },
   { id = 173, name = "centipede" },
   { id = 174, name = "snail" },
   { id = 175, name = "mandrake" },
   { id = 176, name = "beetle" },
   { id = 177, name = "mushroom" },
   { id = 178, name = "mercenary_female" },
   { id = 179, name = "farmer_male" },
   { id = 180, name = "farmer_female" },
   { id = 181, name = "sister_male" },
   { id = 182, name = "sister_female" },
   { id = 183, name = "rogue_male" },
   { id = 184, name = "rogue_female" },
   { id = 185, name = "artist_male" },
   { id = 186, name = "artist_female" },
   { id = 187, name = "miner_male" },
   { id = 188, name = "miner_female" },
   { id = 189, name = "noble_male" },
   { id = 190, name = "noble_female" },
   { id = 191, name = "mutant" },
   { id = 192, name = "balzak" },
   { id = 193, name = "revlus" },
   { id = 194, name = "mage_guild_member_female" },
   { id = 195, name = "mage_guild_member_male" },
   { id = 196, name = "doria" },
   { id = 197, name = "sin" },
   { id = 198, name = "iron_maiden" },
   { id = 199, name = "catgod" },
   { id = 200, name = "bat" },
   { id = 201, name = "ent", tall = true },
   { id = 202, name = "lich" },
   { id = 203, name = "hound" },
   { id = 204, name = "giant_squirrel" },
   { id = 205, name = "ghost" },
   { id = 206, name = "spirit" },
   { id = 207, name = "eye" },
   { id = 208, name = "nurse" },
   { id = 209, name = "puppet" },
   { id = 210, name = "wasp" },
   { id = 211, name = "black_cat" },
   { id = 212, name = "imp" },
   { id = 213, name = "hand" },
   { id = 214, name = "nymph" },
   { id = 215, name = "chaos_flower" },
   { id = 216, name = "snake" },
   { id = 217, name = "cute_fairy" },
   { id = 218, name = "android" },
   { id = 219, name = "tuwen" },
   { id = 220, name = "goblin" },
   { id = 221, name = "baptist" },
   { id = 222, name = "bear" },
   { id = 223, name = "armor" },
   { id = 224, name = "medusa" },
   { id = 225, name = "cupid" },
   { id = 226, name = "phantom" },
   { id = 227, name = "harpy" },
   { id = 228, name = "dragon", tall = true },
   { id = 229, name = "cerberus" },
   { id = 230, name = "spider" },
   { id = 231, name = "golem", tall = true },
   { id = 232, name = "giant", tall = true },
   { id = 233, name = "drake", tall = true },
   { id = 235, name = "wyvern", tall = true },
   { id = 236, name = "black_angel" },
   { id = 237, name = "crab" },
   { id = 238, name = "_238" },
   { id = 239, name = "fire_centipede" },
   { id = 240, name = "cultist_of_fire" },
   { id = 241, name = "skeleton" },
   { id = 242, name = "defender" },
   { id = 243, name = "missionary_of_darkness" },
   { id = 244, name = "piece" },
   { id = 245, name = "rook" },
   { id = 246, name = "bishop" },
   { id = 247, name = "knight" },
   { id = 248, name = "queen" },
   { id = 249, name = "king" },
   { id = 250, name = "yerles_machine_infantry" },
   { id = 251, name = "rock_thrower" },
   { id = 252, name = "metal" },
   { id = 253, name = "cat" },
   { id = 254, name = "dog" },
   { id = 255, name = "catsister" },
   { id = 256, name = "shell" },
   { id = 257, name = "slime" },
   { id = 258, name = "public_performer" },
   { id = 259, name = "twintail" },
   { id = 260, name = "silver_wolf" },
   { id = 262, name = "horse" },
   { id = 263, name = "icolle" },
   { id = 267, name = "golden_knight" },
   { id = 268, name = "_268" },
   { id = 269, name = "exile" },
   { id = 270, name = "machine" },
   { id = 271, name = "deformed_eye" },
   { id = 272, name = "wisp" },
   { id = 273, name = "shining_hedgehog" },
   { id = 274, name = "chicken" },
   { id = 275, name = "pumpkin" },
   { id = 276, name = "stalker" },
   { id = 277, name = "shub_niggurath" },
   { id = 278, name = "gagu" },
   { id = 279, name = "silver_eyed_witch" },
   { id = 280, name = "shade", tall = true },
   { id = 281, name = "quickling" },
   { id = 282, name = "cube" },
   { id = 283, name = "alien" },
   { id = 284, name = "fanatic_female" },
   { id = 285, name = "fanatic_male" },
   { id = 286, name = "_286" },
   { id = 287, name = "_287" },
   { id = 288, name = "_288" },
   { id = 289, name = "_289" },
   { id = 290, name = "_290" },
   { id = 291, name = "_291" },
   { id = 292, name = "_292" },
   { id = 293, name = "_293" },
   { id = 294, name = "_294" },
   { id = 295, name = "_295" },
   { id = 296, name = "_296" },
   { id = 297, name = "zeome", tall = true },
   { id = 307, name = "_307" },
   { id = 331, name = "orphe" },
   { id = 332, name = "mad_scientist" },
   { id = 333, name = "isca" },
   { id = 334, name = "whom_dwell_in_the_vanity" },
   { id = 335, name = "_335" },
   { id = 336, name = "_336" },
   { id = 337, name = "loyter" },
   { id = 338, name = "vesda", tall = true },
   { id = 339, name = "issizzle", tall = true },
   { id = 340, name = "erystia" },
   { id = 341, name = "wynan", tall = true },
   { id = 342, name = "corgon", tall = true },
   { id = 343, name = "quruiza", tall = true },
   { id = 344, name = "dungeon_cleaner" },
   { id = 345, name = "larnneire" },
   { id = 346, name = "lomias" },
   { id = 347, name = "at" },
   { id = 348, name = "frisia" },
   { id = 349, name = "machinegod", tall = true },
   { id = 350, name = "undeadgod" },
   { id = 351, name = "ebon2", tall = true },
   { id = 352, name = "garokk" },
   { id = 353, name = "miral" },
   { id = 354, name = "_354" },
   { id = 355, name = "young_lady" },
   { id = 356, name = "gwen" },
   { id = 357, name = "town_child_female" },
   { id = 358, name = "pael" },
   { id = 359, name = "lily" },
   { id = 360, name = "_360" },
   { id = 361, name = "raphael" },
   { id = 362, name = "ainc" },
   { id = 363, name = "guard_port_kapul" },
   { id = 364, name = "poppy" },
   { id = 365, name = "rilian" },
   { id = 366, name = "tam" },
   { id = 367, name = "carbuncle" },
   { id = 368, name = "lion" },
   { id = 369, name = "cacy" },
   { id = 370, name = "gilbert_the_colonel" },
   { id = 373, name = "yerles_self_propelled_gun" },
   { id = 377, name = "juere_swordman" },
   { id = 378, name = "yeek" },
   { id = 379, name = "hot_spring_maniac_male" },
   { id = 380, name = "hot_spring_maniac_female" },
   { id = 381, name = "rodlob" },
   { id = 383, name = "arnord" },
   { id = 385, name = "kamikaze_samurai" },
   { id = 386, name = "rock" },
   { id = 387, name = "stray_cat" },
   { id = 388, name = "mia" },
   { id = 389, name = "dinosaur", tall = true },
   { id = 390, name = "fairy" },
   { id = 391, name = "troll", tall = true },
   { id = 392, name = "renton" },
   { id = 393, name = "lulwy", tall = true },
   { id = 394, name = "marks" },
   { id = 395, name = "ancient_coffin" },
   { id = 396, name = "scorpion" },
   { id = 397, name = "lizardman" },
   { id = 398, name = "minotaur", tall = true },
   { id = 399, name = "spore_mushroom" },
   { id = 400, name = "bubble" },
   { id = 401, name = "mass_monster" },
   { id = 402, name = "_402" },
   { id = 403, name = "conery" },
   { id = 404, name = "executioner", tall = true },
   { id = 405, name = "asura", tall = true },
   { id = 406, name = "hungry_sea_lion" },
   { id = 407, name = "mad_gaze" },
   { id = 408, name = "big_daddy", tall = true },
   { id = 409, name = "little_sister" },
   { id = 410, name = "cleaner" },
   { id = 411, name = "hard_gay" },
   { id = 412, name = "strange_scientist" },
   { id = 413, name = "ehekatl", tall = true },
   { id = 414, name = "guild_trainer_female" },
   { id = 415, name = "guild_trainer_male" },
   { id = 416, name = "mysterious_producer" },
   { id = 417, name = "prostitute_female" },
   { id = 418, name = "prostitute_male" },
   { id = 419, name = "prisoner_male" },
   { id = 420, name = "prisoner_female" },
   { id = 429, name = "yith", tall = true },
   { id = 430, name = "spiral_king", tall = true },
   { id = 432, name = "opatos", tall = true },
   { id = 433, name = "kumiromi", tall = true },
   { id = 434, name = "mine_dog" },
   { id = 436, name = "_436" },
   { id = 439, name = "mammoth", tall = true },
   { id = 442, name = "holy_beast", tall = true },
   { id = 443, name = "caravan_master" },
   { id = 446, name = "_446" },
   { id = 447, name = "mani", tall = true },
   { id = 448, name = "_448" },
   { id = 449, name = "_449" },
   { id = 450, name = "_450" },
   { id = 451, name = "_451" },
   { id = 452, name = "_452" },
   { id = 467, name = "_467" },
   { id = 468, name = "_468" },
   { id = 470, name = "kaneda_bike" },
   { id = 471, name = "bike" },
   { id = 473, name = "part_time_worker" },
   { id = 476, name = "festival_tourist_female" },
   { id = 477, name = "festival_tourist_male" },
   { id = 478, name = "the_leopard_warrior" },
   { id = 479, name = "silvia" },
   { id = 660, name = "_660" },
}

local misc = {
   { id = 1,  name = "projectile_arrow" },
   { id = 2,  name = "projectile_bullet" },
   { id = 3,  name = "projectile_bolt" },
   { id = 4,  name = "_4" },
   { id = 5,  name = "_5" },
   { id = 6,  name = "projectile_magic_arrow" },
   { id = 7,  name = "particle_spark" },
   { id = 8,  name = "particle_skull" },
   { id = 9,  name = "particle_candle" },
   { id = 10, name = "particle_sweat" },
   { id = 11, name = "_11" },
   { id = 12, name = "_12" },
   { id = 13, name = "_13" },
   { id = 14, name = "_14" },
   { id = 15, name = "_15" },
   { id = 16, name = "_16" },
   { id = 17, name = "_17" },
   { id = 18, name = "_18" },
   { id = 19, name = "mef_slime", count_x = 2 },
   { id = 20, name = "_20" },
   { id = 21, name = "_21" },
   { id = 22, name = "mef_water" },
   { id = 23, name = "_23" },
   { id = 24, name = "mef_fire", count_x = 3 },
   { id = 25, name = "_25" },
   { id = 26, name = "_26" },
   { id = 27, name = "mef_liquid", count_x = 3 },
   { id = 28, name = "_28" },
   { id = 29, name = "_29" },
   { id = 30, name = "mef_barrier", count_x = 2 },
   { id = 31, name = "_31" },
}

local item = {
   { id = 0,   name = "empty" },
   { id = 33,  name = "worthless_fake_gold_bar" },
   { id = 66,  name = "bed" },
   { id = 67,  name = "rag_doll" },
   { id = 68,  name = "noble_toy" },
   { id = 69,  name = "modern_table" },
   { id = 70,  name = "dining_table" },
   { id = 71,  name = "_71" },
   { id = 72,  name = "barrel" },
   { id = 73,  name = "armor" },
   { id = 74,  name = "lot_of_goods" },
   { id = 75,  name = "lot_of_accessories" },
   { id = 76,  name = "goulds_piano" },
   { id = 77,  name = "_77" },
   { id = 78,  name = "bar_table_alpha" },
   { id = 79,  name = "_79" },
   { id = 80,  name = "bar_table_beta" },
   { id = 81,  name = "painting_of_madam" },
   { id = 82,  name = "broken_pillar" },
   { id = 83,  name = "big_table" },
   { id = 84,  name = "modern_chair" },
   { id = 85,  name = "pick" },
   { id = 86,  name = "lantern" },
   { id = 87,  name = "decorative_armor" },
   { id = 88,  name = "anvil" },
   { id = 89,  name = "closed_pot" },
   { id = 90,  name = "open_pot" },
   { id = 91,  name = "academic_table" },
   { id = 92,  name = "painting_of_landscape" },
   { id = 93,  name = "square_chair" },
   { id = 94,  name = "cheap_chair" },
   { id = 95,  name = "cupboard" },
   { id = 96,  name = "barn" },
   { id = 97,  name = "neat_shelf" },
   { id = 98,  name = "closet" },
   { id = 99,  name = "variety_of_tools" },
   { id = 100, name = "variety_of_goods" },
   { id = 101, name = "well" },
   { id = 102, name = "variety_of_clothes" },
   { id = 103, name = "furnace" },
   { id = 104, name = "oven" },
   { id = 105, name = "sign" },
   { id = 106, name = "crossroad_sign" },
   { id = 107, name = "house_board" },
   { id = 108, name = "_108" },
   { id = 109, name = "empty_basket" },
   { id = 110, name = "_110" },
   { id = 111, name = "_111" },
   { id = 112, name = "_112" },
   { id = 113, name = "_113" },
   { id = 114, name = "_114" },
   { id = 115, name = "_115" },
   { id = 116, name = "show_case_of_breads" },
   { id = 117, name = "stick_bread" },
   { id = 118, name = "beaker" },
   { id = 119, name = "alchemy_kit" },
   { id = 120, name = "pentagram" },
   { id = 121, name = "small_foliage_plant" },
   { id = 122, name = "rose" },
   { id = 123, name = "large_foliage_plant" },
   { id = 124, name = "sage" },
   { id = 125, name = "gazania" },
   { id = 126, name = "nerine" },
   { id = 127, name = "anemos" },
   { id = 128, name = "foxtail_grass" },
   { id = 129, name = "carnation" },
   { id = 130, name = "black_crystal" },
   { id = 131, name = "painting_of_sunflower" },
   { id = 132, name = "canvas" },
   { id = 133, name = "map" },
   { id = 134, name = "snow_man" },
   { id = 135, name = "bundle_of_bows" },
   { id = 136, name = "bundle_of_weapons" },
   { id = 137, name = "decorated_cloth" },
   { id = 138, name = "decorated_armor" },
   { id = 139, name = "statue_of_armor" },
   { id = 140, name = "disorderly_book" },
   { id = 141, name = "lot_of_books" },
   { id = 142, name = "craft_rack" },
   { id = 143, name = "craft_book_shelf" },
   { id = 144, name = "lot_of_alcohols" },
   { id = 145, name = "kitchen" },
   { id = 146, name = "washstand" },
   { id = 147, name = "kitchen_oven" },
   { id = 148, name = "narrow_dining_table" },
   { id = 149, name = "elegant_table" },
   { id = 150, name = "gorgeous_candlestick" },
   { id = 151, name = "simple_shelf" },
   { id = 152, name = "sewing_kit" },
   { id = 153, name = "carpenters_tool" },
   { id = 154, name = "messy_cloth" },
   { id = 155, name = "silk_cloth" },
   { id = 156, name = "collapsed_grave" },
   { id = 157, name = "crumbled_grave" },
   { id = 158, name = "grave_of_ornamented_with_flowers" },
   { id = 159, name = "brand_new_grave" },
   { id = 160, name = "solemn_tomb" },
   { id = 161, name = "grave" },
   { id = 162, name = "old_grave" },
   { id = 163, name = "ceremony_altar" },
   { id = 164, name = "green_pea" },
   { id = 165, name = "small_medal" },
   { id = 166, name = "bunk_bed" },
   { id = 167, name = "_167" },
   { id = 168, name = "hero_cheese" },
   { id = 169, name = "quwapana" },
   { id = 170, name = "stomafillia" },
   { id = 171, name = "edible_wild_plant" },
   { id = 172, name = "happy_apple" },
   { id = 173, name = "grape" },
   { id = 174, name = "kiwi" },
   { id = 175, name = "cherry" },
   { id = 176, name = "guava" },
   { id = 177, name = "carrot" },
   { id = 178, name = "radish" },
   { id = 179, name = "sweet_potato" },
   { id = 180, name = "lettuce" },
   { id = 181, name = "stack_of_dishes" },
   { id = 182, name = "imo" },
   { id = 183, name = "api_nut" },
   { id = 184, name = "strawberry" },
   { id = 185, name = "healthy_leaf" },
   { id = 186, name = "rainbow_fruit" },
   { id = 187, name = "qucche" },
   { id = 188, name = "tangerine" },
   { id = 189, name = "magic_fruit" },
   { id = 190, name = "_190" },
   { id = 191, name = "cbocchi" },
   { id = 192, name = "melon" },
   { id = 193, name = "leccho" },
   { id = 194, name = "_194" },
   { id = 195, name = "_195" },
   { id = 196, name = "corpse" },
   { id = 197, name = "shop_strongbox" },
   { id = 198, name = "pot" },
   { id = 199, name = "animal_bone" },
   { id = 200, name = "straw" },
   { id = 201, name = "bomb_fish" },
   { id = 202, name = "rope" },
   { id = 203, name = "bowl" },
   { id = 204, name = "washing" },
   { id = 205, name = "_205" },
   { id = 206, name = "empty_bowl" },
   { id = 207, name = "basket" },
   { id = 208, name = "whisky" },
   { id = 209, name = "ore_piece" },
   { id = 210, name = "bottle_of_whisky" },
   { id = 211, name = "crystal" },
   { id = 212, name = "raw_ore" },
   { id = 213, name = "raw_ore_of_diamond" },
   { id = 214, name = "_214" },
   { id = 215, name = "_215" },
   { id = 216, name = "_216" },
   { id = 217, name = "_217" },
   { id = 218, name = "_218" },
   { id = 219, name = "_219" },
   { id = 220, name = "small_gamble_chest" },
   { id = 221, name = "figurine_of_sword" },
   { id = 222, name = "figurine_of_warrior" },
   { id = 223, name = "molotov" },
   { id = 224, name = "horn" },
   { id = 225, name = "_225" },
   { id = 226, name = "portable_cooking_tool" },
   { id = 227, name = "_227" },
   { id = 228, name = "_228" },
   { id = 229, name = "_229" },
   { id = 230, name = "_230" },
   { id = 231, name = "fire_wood" },
   { id = 232, name = "scarecrow" },
   { id = 233, name = "sack" },
   { id = 234, name = "luxury_drawer" },
   { id = 235, name = "bookshelf" },
   { id = 236, name = "modern_rack" },
   { id = 237, name = "round_chair" },
   { id = 238, name = "junk_stone" },
   { id = 239, name = "wood_piece" },
   { id = 240, name = "garbage" },
   { id = 241, name = "broken_vase" },
   { id = 242, name = "bonfire" },
   { id = 243, name = "flag" },
   { id = 244, name = "broken_sword" },
   { id = 245, name = "bone_fragment" },
   { id = 246, name = "skeleton" },
   { id = 247, name = "tombstone" },
   { id = 248, name = "broom" },
   { id = 249, name = "water_tub" },
   { id = 250, name = "comfortable_table" },
   { id = 251, name = "inner_tube" },
   { id = 252, name = "treasure_map" },
   { id = 253, name = "heir_trunk" },
   { id = 254, name = "wallet" },
   { id = 255, name = "well_kept_armor" },
   { id = 256, name = "rack_of_good" },
   { id = 257, name = "rack_of_accessories" },
   { id = 258, name = "towel" },
   { id = 259, name = "ragged_table" },
   { id = 260, name = "cabinet" },
   { id = 261, name = "luxury_bed" },
   { id = 262, name = "vase" },
   { id = 263, name = "high_grade_dresser" },
   { id = 264, name = "neat_bar_table" },
   { id = 265, name = "large_bouquet" },
   { id = 266, name = "chest_of_clothes" },
   { id = 267, name = "giant_bed" },
   { id = 268, name = "plain_bed" },
   { id = 269, name = "coffin" },
   { id = 270, name = "food_processor" },
   { id = 271, name = "soft_bed" },
   { id = 272, name = "cheap_rack" },
   { id = 273, name = "dresser" },
   { id = 274, name = "clean_bed" },
   { id = 275, name = "bathtub" },
   { id = 276, name = "pachisuro_machine" },
   { id = 277, name = "casino_table" },
   { id = 278, name = "slot_machine" },
   { id = 279, name = "darts_board" },
   { id = 280, name = "big_foliage_plant" },
   { id = 281, name = "old_shelf" },
   { id = 282, name = "old_bookshelf" },
   { id = 283, name = "cheap_bed" },
   { id = 284, name = "cheap_table" },
   { id = 285, name = "neat_rack" },
   { id = 286, name = "simple_dresser" },
   { id = 287, name = "_287" },
   { id = 288, name = "sacred_altar" },
   { id = 289, name = "comfortable_bed" },
   { id = 290, name = "simple_rack" },
   { id = 291, name = "wide_chair" },
   { id = 292, name = "piano" },
   { id = 293, name = "statue_of_cross" },
   { id = 294, name = "stump" },
   { id = 295, name = "dress" },
   { id = 296, name = "table" },
   { id = 297, name = "travelers_food" },
   { id = 298, name = "_298" },
   { id = 299, name = "golden_pedestal" },
   { id = 300, name = "golden_statue" },
   { id = 301, name = "rabbits_tail" },
   { id = 302, name = "remains_blood" },
   { id = 303, name = "remains_eye" },
   { id = 304, name = "remains_heart" },
   { id = 305, name = "remains_bone" },
   { id = 306, name = "fishing_pole" },
   { id = 307, name = "rune" },
   { id = 308, name = "deed" },
   { id = 309, name = "moonfish" },
   { id = 310, name = "fish" },
   { id = 311, name = "flatfish" },
   { id = 312, name = "manboo" },
   { id = 313, name = "seabream" },
   { id = 314, name = "salmon" },
   { id = 315, name = "globefish" },
   { id = 316, name = "tuna_fish" },
   { id = 317, name = "cutlassfish" },
   { id = 318, name = "sandborer" },
   { id = 319, name = "gem_cutter" },
   { id = 320, name = "red_treasure_machine" },
   { id = 321, name = "blue_treasure_machine" },
   { id = 322, name = "rare_treasure_ball" },
   { id = 323, name = "seed" },
   { id = 324, name = "sleeping_bag" },
   { id = 325, name = "salary_chest" },
   { id = 326, name = "feather" },
   { id = 327, name = "_327" },
   { id = 328, name = "_328" },
   { id = 329, name = "_329" },
   { id = 330, name = "shelter" },
   { id = 331, name = "masters_delivery_chest" },
   { id = 332, name = "register" },
   { id = 333, name = "book" },
   { id = 334, name = "textbook" },
   { id = 335, name = "blanket" },
   { id = 336, name = "_336" },
   { id = 337, name = "jerky" },
   { id = 338, name = "egg" },
   { id = 339, name = "bottle_of_milk" },
   { id = 340, name = "shit" },
   { id = 341, name = "_341" },
   { id = 342, name = "_342" },
   { id = 343, name = "_343" },
   { id = 344, name = "_344" },
   { id = 345, name = "_345" },
   { id = 346, name = "_346" },
   { id = 347, name = "_347" },
   { id = 348, name = "kitty_bank" },
   { id = 349, name = "campfire", count_x = 3 },
   { id = 350, name = "_350" },
   { id = 351, name = "_351" },
   { id = 352, name = "torch" },
   { id = 353, name = "candle" },
   { id = 354, name = "potion" },
   { id = 355, name = "fountain", count_x = 3 },
   { id = 356, name = "_356" },
   { id = 357, name = "_357" },
   { id = 358, name = "_358" },
   { id = 359, name = "_359" },
   { id = 360, name = "dish" },
   { id = 363, name = "_363" },
   { id = 364, name = "fancy_lamp" },
   { id = 365, name = "handful_of_snow" },
   { id = 366, name = "mini_snow_man" },
   { id = 367, name = "snow_scarecrow" },
   { id = 368, name = "snow_barrel" },
   { id = 369, name = "stained_glass_window" },
   { id = 370, name = "giants_shackle" },
   { id = 371, name = "empty_bottle" },
   { id = 372, name = "holy_well" },
   { id = 373, name = "presidents_chair" },
   { id = 374, name = "green_plant" },
   { id = 375, name = "money_tree" },
   { id = 376, name = "barbecue_set" },
   { id = 377, name = "giant_cactus" },
   { id = 378, name = "square_window" },
   { id = 379, name = "window" },
   { id = 380, name = "triangle_plant" },
   { id = 381, name = "board" },
   { id = 382, name = "nice_window" },
   { id = 383, name = "bill" },
   { id = 384, name = "tax_masters_tax_box" },
   { id = 385, name = "_385" },
   { id = 386, name = "_386" },
   { id = 387, name = "_387" },
   { id = 388, name = "_388" },
   { id = 389, name = "_389" },
   { id = 390, name = "_390" },
   { id = 391, name = "gift" },
   { id = 392, name = "pan_flute" },
   { id = 393, name = "alud" },
   { id = 394, name = "harmonica" },
   { id = 395, name = "harp" },
   { id = 396, name = "breastplate" },
   { id = 398, name = "decorative_amulet" },
   { id = 399, name = "bardiche" },
   { id = 400, name = "dagger" },
   { id = 401, name = "spear" },
   { id = 402, name = "skull_bow" },
   { id = 403, name = "_403" },
   { id = 404, name = "long_bow" },
   { id = 405, name = "long_sword" },
   { id = 406, name = "_406" },
   { id = 407, name = "decorative_ring" },
   { id = 408, name = "robe" },
   { id = 409, name = "banded_mail" },
   { id = 410, name = "plate_mail" },
   { id = 411, name = "knight_shield" },
   { id = 412, name = "bolt" },
   { id = 413, name = "feather_hat" },
   { id = 414, name = "plate_gauntlets" },
   { id = 415, name = "holy_lance" },
   { id = 416, name = "_416" },
   { id = 418, name = "heavy_boots" },
   { id = 419, name = "pistol" },
   { id = 420, name = "bullet" },
   { id = 421, name = "scythe" },
   { id = 422, name = "light_cloak" },
   { id = 423, name = "girdle" },
   { id = 424, name = "stone" },
   { id = 425, name = "staff" },
   { id = 426, name = "halberd" },
   { id = 427, name = "club" },
   { id = 428, name = "_428" },
   { id = 429, name = "spellbook" },
   { id = 430, name = "_430" },
   { id = 431, name = "katana" },
   { id = 432, name = "wakizashi" },
   { id = 433, name = "gold_piece" },
   { id = 434, name = "_434" },
   { id = 435, name = "_435" },
   { id = 436, name = "_436" },
   { id = 437, name = "platinum_coin" },
   { id = 438, name = "material_box" },
   { id = 440, name = "ring_mail" },
   { id = 441, name = "composite_mail" },
   { id = 442, name = "chain_mail" },
   { id = 443, name = "pope_robe" },
   { id = 444, name = "light_mail" },
   { id = 445, name = "coat" },
   { id = 446, name = "breast_plate" },
   { id = 447, name = "bulletproof_jacket" },
   { id = 448, name = "gloves" },
   { id = 449, name = "decorated_gloves" },
   { id = 450, name = "thick_gauntlets" },
   { id = 451, name = "light_gloves" },
   { id = 452, name = "composite_gauntlets" },
   { id = 453, name = "small_shield" },
   { id = 454, name = "round_shield" },
   { id = 455, name = "shield" },
   { id = 456, name = "large_shield" },
   { id = 457, name = "kite_shield" },
   { id = 458, name = "tower_shield" },
   { id = 459, name = "tight_boots" },
   { id = 460, name = "composite_boots" },
   { id = 461, name = "armored_boots" },
   { id = 470, name = "scroll" },
   { id = 471, name = "rod" },
   { id = 472, name = "_472" },
   { id = 473, name = "boots" },
   { id = 474, name = "composite_girdle" },
   { id = 475, name = "armored_cloak" },
   { id = 476, name = "cloak" },
   { id = 477, name = "magic_hat" },
   { id = 478, name = "fairy_hat" },
   { id = 479, name = "helm" },
   { id = 480, name = "knight_helm" },
   { id = 481, name = "heavy_helm" },
   { id = 482, name = "composite_helm" },
   { id = 483, name = "engagement_amulet" },
   { id = 484, name = "bejeweled_amulet" },
   { id = 485, name = "charm" },
   { id = 486, name = "neck_guard" },
   { id = 487, name = "talisman" },
   { id = 488, name = "peridot" },
   { id = 489, name = "engagement_ring" },
   { id = 490, name = "ring" },
   { id = 491, name = "armored_ring" },
   { id = 492, name = "composite_ring" },
   { id = 493, name = "stethoscope" },
   { id = 494, name = "trident" },
   { id = 495, name = "_495" },
   { id = 496, name = "_496" },
   { id = 497, name = "_497" },
   { id = 498, name = "crossbow" },
   { id = 499, name = "hand_axe" },
   { id = 500, name = "battle_axe" },
   { id = 501, name = "zantetsu" },
   { id = 502, name = "scimitar" },
   { id = 503, name = "claymore" },
   { id = 504, name = "hammer" },
   { id = 505, name = "long_staff" },
   { id = 506, name = "training_machine" },
   { id = 507, name = "machine" },
   { id = 508, name = "computer" },
   { id = 509, name = "camera" },
   { id = 510, name = "microwave_oven" },
   { id = 511, name = "server" },
   { id = 512, name = "storage" },
   { id = 513, name = "trash_can" },
   { id = 514, name = "shot_gun" },
   { id = 515, name = "chip" },
   { id = 516, name = "playback_disc" },
   { id = 517, name = "pop_corn" },
   { id = 518, name = "fried_potato" },
   { id = 519, name = "cyber_snack" },
   { id = 520, name = "laser_gun" },
   { id = 521, name = "energy_cell" },
   { id = 522, name = "wing" },
   { id = 523, name = "food_maker", tall = true },
   { id = 524, name = "long_pillar", tall = true },
   { id = 525, name = "statue_ornamented_with_plants", tall = true },
   { id = 526, name = "statue_ornamented_with_flowers", tall = true },
   { id = 527, name = "tree_of_beech", tall = true },
   { id = 528, name = "card" },
   { id = 530, name = "_530" },
   { id = 531, name = "figurine", tall = true },
   { id = 532, name = "town_book" },
   { id = 533, name = "deck" },
   { id = 534, name = "whistle" },
   { id = 535, name = "vomit" },
   { id = 536, name = "shuriken" },
   { id = 537, name = "grenade" },
   { id = 538, name = "token_of_friendship" },
   { id = 539, name = "fortune_cookie" },
   { id = 540, name = "tomato" },
   { id = 541, name = "large_bookshelf" },
   { id = 542, name = "special_steamed_meat_bun" },
   { id = 543, name = "luxury_sofa" },
   { id = 544, name = "deer_head" },
   { id = 545, name = "fur_carpet" },
   { id = 546, name = "kitchen_knife" },
   { id = 547, name = "machine_gun" },
   { id = 548, name = "_548" },
   { id = 549, name = "recipe_holder" },
   { id = 550, name = "recipe" },
   { id = 551, name = "sack_of_sugar" },
   { id = 552, name = "puff_puff_bread" },
   { id = 553, name = "bottle_of_salt" },
   { id = 554, name = "pot_for_testing" },
   { id = 555, name = "frying_pan_for_testing" },
   { id = 563, name = "sand_bag", tall = true },
   { id = 564, name = "figurine_tall", tall = true },
   { id = 566, name = "moon_gate", tall = true },
   { id = 567, name = "moon_gate_b", tall = true },
   { id = 568, name = "flower_arch", tall = true },
   { id = 569, name = "bait", tall = true },
   { id = 570, name = "christmas_tree", tall = true },
   { id = 571, name = "pillar", tall = true },
   { id = 572, name = "statue_of_holy_cross", tall = true },
   { id = 573, name = "modern_lamp_b", tall = true },
   { id = 574, name = "tree_of_fir", tall = true },
   { id = 575, name = "tree_of_naked", tall = true },
   { id = 576, name = "modern_lamp_a", tall = true },
   { id = 577, name = "freezer", tall = true },
   { id = 578, name = "statue_of_cat", tall = true },
   { id = 579, name = "throne", tall = true },
   { id = 580, name = "rack_of_potions", tall = true },
   { id = 581, name = "stove", tall = true },
   { id = 582, name = "giant_foliage_plant", tall = true },
   { id = 583, name = "furnance", tall = true },
   { id = 584, name = "fireplace", tall = true },
   { id = 585, name = "street_lamp", tall = true },
   { id = 586, name = "big_cupboard", tall = true },
   { id = 587, name = "tree_of_ash", tall = true },
   { id = 588, name = "tree_of_palm", tall = true },
   { id = 589, name = "tree_of_zelkova", tall = true },
   { id = 590, name = "dead_tree", tall = true },
   { id = 591, name = "tree_of_fruits", tall = true },
   { id = 592, name = "tree_of_fruitless", tall = true },
   { id = 593, name = "tree_of_cedar", tall = true },
   { id = 627, name = "shrine_gate" },
   { id = 628, name = "disguise_set" },
   { id = 629, name = "material_kit" },
   { id = 630, name = "panty" },
   { id = 631, name = "leash" },
   { id = 632, name = "mine" },
   { id = 633, name = "skeleton_key" },
   { id = 634, name = "lockpick" },
   { id = 635, name = "unicorn_horn" },
   { id = 636, name = "cooler_box" },
   { id = 637, name = "rice_barrel" },
   { id = 638, name = "eastern_bed" },
   { id = 639, name = "decorated_window" },
   { id = 640, name = "king_drawer" },
   { id = 641, name = "menu_board" },
   { id = 642, name = "black_board" },
   { id = 643, name = "sofa" },
   { id = 644, name = "flowerbed" },
   { id = 645, name = "toilet" },
   { id = 646, name = "craft_cupboard" },
   { id = 647, name = "sink" },
   { id = 648, name = "junk" },
   { id = 649, name = "double_bed" },
   { id = 650, name = "eastern_lamp" },
   { id = 651, name = "eastern_window" },
   { id = 652, name = "chochin" },
   { id = 653, name = "partition" },
   { id = 654, name = "monster_heart" },
   { id = 655, name = "_655" },
   { id = 656, name = "secret_treasure" },
   { id = 657, name = "gemstone" },
   { id = 658, name = "monster_ball" },
   { id = 659, name = "eastern_partition" },
   { id = 662, name = "summoning_crystal" },
   { id = 663, name = "_663" },
   { id = 664, name = "downstairs" },
   { id = 665, name = "upstairs" },
   { id = 666, name = "new_years_gift" },
   { id = 667, name = "kotatsu" },
   { id = 668, name = "daruma" },
   { id = 669, name = "kagami_mochi" },
   { id = 670, name = "mochi" },
   { id = 671, name = "lightsabre" },
   { id = 672, name = "festival_wreath" },
   { id = 673, name = "pedestal" },
   { id = 674, name = "counter" },
   { id = 675, name = "jures_body_pillow" },
   { id = 676, name = "new_years_decoration" },
   { id = 677, name = "miniature_tree" },
   { id = 678, name = "bottle_of_soda" },
   { id = 679, name = "blue_capsule_drug" },
   { id = 680, name = "statue_of_opatos", tall = true },
   { id = 681, name = "statue_of_kumiromi", tall = true },
   { id = 682, name = "statue_of_mani", tall = true },
   { id = 683, name = "luxury_cabinet", tall = true },
   { id = 684, name = "blue_stall", tall = true },
   { id = 685, name = "red_stall", tall = true },
   { id = 686, name = "statue_of_creator", tall = true },
   { id = 687, name = "statue_of_ehekatl", tall = true },
   { id = 688, name = "guillotine", tall = true },
   { id = 689, name = "iron_maiden", tall = true },
   { id = 690, name = "statue_of_jure", tall = true },
   { id = 691, name = "gene_machine", tall = true },
   { id = 692, name = "statue_of_lulwy", tall = true },
   { id = 695, name = "putitoro" },
   { id = 696, name = "_696" },
   { id = 697, name = "dragon_slayer" },
   { id = 698, name = "claymore_unique" },
   { id = 699, name = "stradivarius" },
}

local feat = {
   { id = 231, name = "stairs_down" },
   { id = 232, name = "stairs_up" },
   { id = 233, name = "hidden" },
   { id = 234, name = "trap" },
   { id = 235, name = "bar" },
   { id = 236, name = "door_wooden_open" },
   { id = 237, name = "hatch" },
   { id = 238, name = "material_dig" },
   { id = 239, name = "material_gem" },
   { id = 240, name = "material_wood" },
   { id = 241, name = "door_sf_open" },
   { id = 242, name = "pot" },
   { id = 243, name = "material_crafting" },
   { id = 244, name = "material_mine" },
   { id = 245, name = "material_fish" },
   { id = 246, name = "material_plant" },
   { id = 247, name = "plant_1" },
   { id = 248, name = "plant_2" },
   { id = 249, name = "plant_3" },
   { id = 250, name = "ant" },
   -- { id = 251, name = "feat_251" },
   -- { id = 252, name = "feat_252" },
   { id = 284, name = "moongate", tall = true, count_x = 2 },
   -- { id = 285, name = "feat_285" },
   { id = 264, name = "door_eastern_open" },
   { id = 265, name = "door_jail_open" },
   { id = 726, name = "door_wooden_closed" },
   { id = 727, name = "quest_board" },
   { id = 728, name = "door_sf_closed" },
   { id = 729, name = "voting_box" },
   { id = 730, name = "door_eastern_closed" },
   { id = 731, name = "tomb" },
   { id = 732, name = "politics_board" },
   { id = 733, name = "door_jail_closed" }
}

local area = {
   { id = 132, name = "area_city" },
   { id = 133, name = "area_cave" },
   { id = 134, name = "area_rock" },
   { id = 135, name = "area_tree" },
   { id = 136, name = "area_palace" },
   { id = 137, name = "area_tower" },
   { id = 138, name = "area_your_dungeon" },
   { id = 139, name = "area_lesimas" },
   { id = 140, name = "area_temple" },
   { id = 141, name = "area_crypt" },
   { id = 142, name = "area_village" },
   { id = 143, name = "area_town" },
   { id = 144, name = "area_castle" },
   { id = 145, name = "area_tower_of_fire" },
   { id = 146, name = "area_dungeon" },
   { id = 147, name = "area_truce_ground" },
   { id = 148, name = "area_tent" },
   { id = 149, name = "area_god" },
   { id = 150, name = "area_museum" },
   { id = 151, name = "area_shop" },
   { id = 152, name = "area_crop" },
   { id = 153, name = "area_storage_house" },
   { id = 154, name = "area_ranch" },
   { id = 155, name = "area_embassy" },
   { id = 156, name = "area_village_snow" },
   { id = 157, name = "area_miral_and_garoks_workshop" },
   { id = 158, name = "area_border_tent" },
   { id = 159, name = "area_the_smoke_and_pipe" },
   { id = 160, name = "area_pyramid" },
   { id = 161, name = "area_jail" },
   { id = 363, name = "building_mountain" },
   { id = 364, name = "building_crop" },
   { id = 365, name = "building_house_1" },
   { id = 366, name = "building_house_2" },
   { id = 367, name = "building_house_3" },
   { id = 368, name = "building_lighthouse" },
}

local function gen_crop(list, source, folder)
   local l = {}
   for _, v in ipairs(list) do
      local height = 48
      if v.tall then
         height = 96
      end

      local width = 48

      local id = v.id
      local x = (id % 33) * 48
      local y = math.floor(id / 33) * 48

      local output = string.format("graphic/%s/%s.png", folder, v.name)

      l[#l+1] = {
         type = "crop",
         source = source,
         x = x,
         y = y,
         width = width,
         height = height,
         output = output,
         count_x = v.count_x,
         combine_multiple = true,
      }
   end

   return l
end

chara = gen_crop(chara, "graphic/character.bmp", "chara")
item = gen_crop(item, "graphic/item.bmp", "item")
misc = gen_crop(misc, "graphic/item.bmp", "misc")
feat = gen_crop(feat, "graphic/map1.bmp", "feat")
area = gen_crop(area, "graphic/map0.bmp", "feat")

return {
   chara = chara,
   item = item,
   feat = feat,
   area = area,
   misc = misc,
}
